// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ipcAccountsList: () => typedError<AccountsListResponse, IpcError>(__TAURI_INVOKE("ipc_accounts_list")),
	ipcAccountSwitch: (input: AccountSwitchInput) => typedError<AuthAccount, IpcError>(__TAURI_INVOKE("ipc_account_switch", { input })),
	authSavePatToken: (input: SavePatTokenInput) => typedError<AuthAccount, IpcError>(__TAURI_INVOKE("auth_save_pat_token", { input })),
	authTestEndpoints: (host: string) => typedError<EndpointTestResult, IpcError>(__TAURI_INVOKE("auth_test_endpoints", { host })),
	ipcInboxList: (input: InboxListInput) => typedError<InboxItem[], IpcError>(__TAURI_INVOKE("ipc_inbox_list", { input })),
	ipcPrDetailSummary: (input: PrHandleInput) => typedError<{
	account_id: string,
	pr_id: string,
	repo_id: string,
	pr_number: number,
	title: string,
	body: string,
	state: string,
	draft: boolean,
	base_ref: string,
	base_sha: string,
	head_ref: string,
	head_sha: string,
	mergeable_state: string | null,
	merge_state_status: string | null,
	merge_commit_allowed: boolean | null,
	squash_merge_allowed: boolean | null,
	rebase_merge_allowed: boolean | null,
	delete_branch_on_merge_default: boolean | null,
	viewer_can_merge: boolean | null,
	viewer_can_enable_auto_merge: boolean | null,
	viewer_can_disable_auto_merge: boolean | null,
	viewer_can_update_branch: boolean | null,
	viewer_can_delete_head_ref: boolean | null,
	auto_merge_enabled: boolean | null,
	auto_merge_method: string | null,
	auto_merge_commit_headline: string | null,
	auto_merge_commit_body: string | null,
	auto_merge_enabled_by_login: string | null,
	auto_merge_enabled_at: number | null,
	merge_queue_entry_id: string | null,
	merge_queue_entry_position: number | null,
	merge_queue_entry_state: string | null,
	merge_queue_entry_estimated_ms: number | null,
	branch_protection_summary_json: string | null,
	repo_has_merge_queue: boolean | null,
	head_ref_state: string | null,
	additions: number,
	deletions: number,
	changed_files: number,
	comment_count: number,
	review_count: number,
	thread_count: number,
	check_run_count: number,
	file_count: number,
	updated_at: number,
	body_server_adjusted: boolean,
	pending_overlay: PendingOverlay | null,
} | null, IpcError>(__TAURI_INVOKE("ipc_pr_detail_summary", { input })),
	listPrPushes: (prId: string) => typedError<PrPushView[], IpcError>(__TAURI_INVOKE("list_pr_pushes", { prId })),
	computeRangeDiff: (prId: string, baseSha: string, oldHeadSha: string, newHeadSha: string) => typedError<RangeDiff, IpcError>(__TAURI_INVOKE("compute_range_diff", { prId, baseSha, oldHeadSha, newHeadSha })),
	ipcPrTimeline: (input: PagedPrInput) => typedError<TimelinePage, IpcError>(__TAURI_INVOKE("ipc_pr_timeline", { input })),
	ipcPrReviewThreads: (input: PagedPrInput) => typedError<ReviewThreadsPage, IpcError>(__TAURI_INVOKE("ipc_pr_review_threads", { input })),
	listSuggestionBlocks: (input: PrHandleInput) => typedError<SuggestionBlock[], IpcError>(__TAURI_INVOKE("list_suggestion_blocks", { input })),
	ipcPrCheckSummary: (input: CheckSummaryInput) => typedError<PrCheckSummary, IpcError>(__TAURI_INVOKE("ipc_pr_check_summary", { input })),
	listCheckAnnotations: (input: PrHandleInput) => typedError<CheckAnnotationView[], IpcError>(__TAURI_INVOKE("list_check_annotations", { input })),
	listCheckAnnotationsForFile: (input: CheckAnnotationsFileInput) => typedError<CheckAnnotationView[], IpcError>(__TAURI_INVOKE("list_check_annotations_for_file", { input })),
	startCheckLogStream: (input: CheckLogStreamInput) => typedError<StreamHandle, IpcError>(__TAURI_INVOKE("start_check_log_stream", { input })),
	ipcPrFiles: (input: PrFilesInput) => typedError<PrFilesResponse, IpcError>(__TAURI_INVOKE("ipc_pr_files", { input })),
	ipcPrPatch: (input: PrPatchInput) => typedError<PrPatchResponse, IpcError>(__TAURI_INVOKE("ipc_pr_patch", { input })),
	getPrFileBlob: (input: PrFileBlobInput) => typedError<PrFileBlobResponse, IpcError>(__TAURI_INVOKE("get_pr_file_blob", { input })),
	ipcRenderedCommentHtml: (input: RenderedCommentInput) => typedError<RenderedCommentHtml, IpcError>(__TAURI_INVOKE("ipc_rendered_comment_html", { input })),
	ipcNotificationsList: (input: NotificationsListInput) => typedError<NotificationItem[], IpcError>(__TAURI_INVOKE("ipc_notifications_list", { input })),
	ipcSystemStatus: (input: SystemStatusInput) => typedError<SystemStatusResponse, IpcError>(__TAURI_INVOKE("ipc_system_status", { input })),
	ipcRepoSubscriptions: (input: RepoSubscriptionsInput) => typedError<RepoSubscriptionItem[], IpcError>(__TAURI_INVOKE("ipc_repo_subscriptions", { input })),
	ipcPrMetadata: (input: PrHandleInput) => typedError<PrMetadataResponse, IpcError>(__TAURI_INVOKE("ipc_pr_metadata", { input })),
	ipcInitInbox: () => typedError<InitInboxResponse, IpcError>(__TAURI_INVOKE("ipc_init_inbox")),
	submitReviewComment: (input: SubmitReviewCommentInput) => typedError<SubmittedMutation, IpcError>(__TAURI_INVOKE("submit_review_comment", { input })),
	submitMutation: (accountId: string, kind: MutationKind, payloadJson: string) => typedError<SubmittedMutation, IpcError>(__TAURI_INVOKE("submit_mutation", { accountId, kind, payloadJson })),
	listPendingMutations: (accountId: string, includePending: boolean | null) => typedError<PendingMutationView[], IpcError>(__TAURI_INVOKE("list_pending_mutations", { accountId, includePending })),
	retryMutation: (mutationId: string) => typedError<null, IpcError>(__TAURI_INVOKE("retry_mutation", { mutationId })),
	discardMutation: (mutationId: string) => typedError<null, IpcError>(__TAURI_INVOKE("discard_mutation", { mutationId })),
	listDrafts: (input: ListDraftsInput) => typedError<Draft[], IpcError>(__TAURI_INVOKE("list_drafts", { input })),
	saveDraft: (input: SaveDraftInput) => typedError<Draft, IpcError>(__TAURI_INVOKE("save_draft", { input })),
	deleteDraft: (draftId: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_draft", { draftId })),
	listSavedReplies: (accountId: string) => typedError<SavedReply[], IpcError>(__TAURI_INVOKE("list_saved_replies", { accountId })),
	createSavedReply: (accountId: string, name: string, body: string) => typedError<SavedReply, IpcError>(__TAURI_INVOKE("create_saved_reply", { accountId, name, body })),
	updateSavedReply: (id: number, name: string, body: string) => typedError<SavedReply, IpcError>(__TAURI_INVOKE("update_saved_reply", { id, name, body })),
	deleteSavedReply: (id: number) => typedError<null, IpcError>(__TAURI_INVOKE("delete_saved_reply", { id })),
	reorderSavedReplies: (input: ReorderSavedRepliesInput) => typedError<null, IpcError>(__TAURI_INVOKE("reorder_saved_replies", { input })),
	importSavedRepliesFromGithub: (accountId: string) => typedError<SavedReply[], IpcError>(__TAURI_INVOKE("import_saved_replies_from_github", { accountId })),
	uploadImageToGithubUserContent: (accountId: string, imageBytes: number[], mime: string) => typedError<ImageUploadResult, IpcError>(__TAURI_INVOKE("upload_image_to_github_user_content", { accountId, imageBytes, mime })),
	renderPreview: (input: RenderPreviewInput) => typedError<RenderedCommentHtml, IpcError>(__TAURI_INVOKE("render_preview", { input })),
	listWorktrees: (accountId: string) => typedError<WorktreeView[], IpcError>(__TAURI_INVOKE("list_worktrees", { accountId })),
	setWorktreeManualOverride: (worktreeId: string, prId: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("set_worktree_manual_override", { worktreeId, prId })),
	setWorktreeRoots: (roots: string[]) => typedError<string[], IpcError>(__TAURI_INVOKE("set_worktree_roots", { roots })),
	listWorktreeRoots: () => typedError<string[], IpcError>(__TAURI_INVOKE("list_worktree_roots")),
	rediscoverWorktrees: () => typedError<RediscoverSummary, IpcError>(__TAURI_INVOKE("rediscover_worktrees")),
	cleanupWorktree: (worktreeId: string, force: boolean) => typedError<CleanupOutcome, CleanupError>(__TAURI_INVOKE("cleanup_worktree", { worktreeId, force })),
	listStacks: (input: StackListInput) => typedError<StackGraph[], IpcError>(__TAURI_INVOKE("list_stacks", { input })),
	startRebaseStack: (input: StackActionInput) => typedError<string, IpcError>(__TAURI_INVOKE("start_rebase_stack", { input })),
	startMergeStack: (input: StackMergeActionInput) => typedError<string, IpcError>(__TAURI_INVOKE("start_merge_stack", { input })),
	resumeStackOp: (input: StackOperationLookupInput) => typedError<null, IpcError>(__TAURI_INVOKE("resume_stack_op", { input })),
	abortStackOp: (input: StackOperationLookupInput) => typedError<null, IpcError>(__TAURI_INVOKE("abort_stack_op", { input })),
	getStackOp: (input: StackOperationLookupInput) => typedError<{
	id: string,
	stack_id: string,
	account_id: string,
	op_kind: StackOperationKind,
	status: StackOperationStatus,
	current_pr_id: string | null,
	current_step: number | null,
	total_steps: number | null,
	worktree_path: string | null,
	conflict_files: string[],
	last_error: string | null,
	started_at: number,
	updated_at: number,
	finished_at: number | null,
} | null, IpcError>(__TAURI_INVOKE("get_stack_op", { input })),
	getGraphiteStatus: () => typedError<GraphiteIntegrationStatus, IpcError>(__TAURI_INVOKE("get_graphite_status")),
	setGraphiteEnabled: (enabled: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_graphite_enabled", { enabled })),
	listNotificationRules: (accountId: string) => typedError<NotificationRule[], IpcError>(__TAURI_INVOKE("list_notification_rules", { accountId })),
	setNotificationRule: (accountId: string, kind: string, enabled: boolean, configJson: string) => typedError<null, IpcError>(__TAURI_INVOKE("set_notification_rule", { accountId, kind, enabled, configJson })),
	setQuietHours: (accountId: string, json: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("set_quiet_hours", { accountId, json })),
	setFocusMode: (accountId: string, on: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_focus_mode", { accountId, on })),
	setPerRepoFilters: (accountId: string, allow: string[], deny: string[]) => typedError<null, IpcError>(__TAURI_INVOKE("set_per_repo_filters", { accountId, allow, deny })),
	listNotificationEvents: (accountId: string, limit: number | null, offset: number | null, since: number | null) => typedError<NotificationEventRow[], IpcError>(__TAURI_INVOKE("list_notification_events", { accountId, limit, offset, since })),
	markNotificationEventSeen: (eventId: string) => typedError<null, IpcError>(__TAURI_INVOKE("mark_notification_event_seen", { eventId })),
	notifDebugSimulateEvent: (accountId: string, payloadJson: string) => typedError<{
	event_id: string,
	account_id: string,
	repo_id: string | null,
	pr_id: string | null,
	event_type: string,
	actor_id: string,
	server_event_id: string,
	title: string,
	body: string,
	fired_at: number,
	deduped: boolean,
} | null, IpcError>(__TAURI_INVOKE("__notif_debug__simulate_event", { accountId, payloadJson })),
};

/** Events */
export const events = {
	inboxAccountIdChanged: makeEvent<InboxChangedEventPayload>("inbox:account:<id> changed"),
	mergeableBackoffAccountIdPrIdTick: makeEvent<MergeableBackoffTickEventPayload>("mergeable_backoff:<account_id>:<pr_id> tick"),
	mutationApplied: makeEvent<MutationAppliedEventPayload>("mutation:applied"),
	mutationFailed: makeEvent<MutationFailedEventPayload>("mutation:failed"),
	mutationHardConflict: makeEvent<MutationHardConflictEventPayload>("mutation:hard-conflict"),
	mutationReconciled: makeEvent<MutationReconciledEventPayload>("mutation:reconciled"),
	mutationRolledBack: makeEvent<MutationRolledBackEventPayload>("mutation:rolled-back"),
	mutationSubmitted: makeEvent<MutationSubmittedEventPayload>("mutation:submitted"),
	networkAccountIdChanged: makeEvent<NetworkChangedEventPayload>("network:<account_id> changed"),
	notificationEvent: makeEvent<NotificationEventPayload>("notification:event"),
	notificationsAccountIdChanged: makeEvent<NotificationsChangedEventPayload>("notifications:account:<id> changed"),
	prIdChanged: makeEvent<PrChangedEventPayload>("pr:<id> changed"),
	rateLimitAccountIdChanged: makeEvent<RateLimitChangedEventPayload>("rate_limit:account:<id> changed"),
	rateLimitBypassAccount: makeEvent<RateLimitBypassEventPayload>("rate_limit_bypass:<account>"),
	rateLimitPressureAccount: makeEvent<RateLimitPressureEventPayload>("rate_limit_pressure:<account>"),
	stackOpOpId: makeEvent<StackOperationEventPayload>("stack_op:<op_id>"),
	stacksAccountIdRepoIdChanged: makeEvent<StacksChangedEventPayload>("stacks:<account_id>:<repo_id> changed"),
	syncAccountIdReconciled: makeEvent<SyncReconciledEventPayload>("sync:<account_id> reconciled"),
	worktreeIdChanged: makeEvent<WorktreeChangedEventPayload>("worktree:<id> changed"),
	worktreeDiscoveryCompleted: makeEvent<WorktreeDiscoveryCompletedEventPayload>("worktree:discovery completed"),
};

/* Types */
export type AccountLocator = {
	host: string,
	login: string,
};

export type AccountSwitchInput = {
	host: string,
	login: string,
};

export type AccountsListResponse = {
	active: AccountLocator | null,
	accounts: AuthAccount[],
};

export type AuthAccount = {
	host: string,
	login: string,
	api_base_url: string,
	graphql_url: string,
	token_kind: string,
	scopes: string[],
	created_at: number,
	updated_at: number,
	is_active: boolean,
};

export type BlockedByReason = {
	kind: string,
	detail: string,
};

export type CheckAnnotationView = {
	annotation_id: string,
	check_run_id: string,
	check_suite_id: string,
	check_run_rest_id: number | null,
	check_run_name: string,
	check_run_status: string,
	check_run_conclusion: string | null,
	check_run_details_url: string | null,
	check_run_head_sha: string | null,
	is_outdated: boolean,
	path: string,
	start_line: number,
	end_line: number,
	start_column: number | null,
	end_column: number | null,
	annotation_level: string,
	title: string | null,
	message: string,
	raw_details: string | null,
	anchor_line: number,
	anchor_side: string,
	anchor_path: string,
	anchor_signature_hash: string,
};

export type CheckAnnotationsFileInput = {
	account_id: string,
	pr_id: string,
	path: string,
};

export type CheckLogStreamInput = {
	check_run_id: string,
	tail_lines: number | null,
};

export type CheckRunSummary = {
	id: string,
	check_suite_id: string,
	rest_id: number | null,
	name: string,
	status: string,
	conclusion: string | null,
	details_url: string | null,
	started_at: number | null,
	completed_at: number | null,
	app_name: string | null,
	check_suite_status: string | null,
	check_suite_conclusion: string | null,
	check_run_head_sha: string | null,
};

export type CheckSummaryInput = {
	account_id: string,
	pr_id: string,
};

export type CleanupError = { kind: "NotFound" } | { kind: "UserManaged" } | { kind: "DirtyState" } | { kind: "ForceRequired" } | { kind: "SnapshotFailed"; detail: string };

export type CleanupOutcome = {
	worktree_id: string,
	snapshot_id: string | null,
	blocked_reason: string | null,
	dirty_detected: boolean,
	would_remove: boolean,
	removed: boolean,
};

export type CommitMetadata = {
	sha: string,
	title: string,
	body: string,
	author_name: string | null,
	committed_at: number | null,
	patch_hash: string,
	file_paths: string[],
	additions: number,
	deletions: number,
};

export type CommitPair = {
	status: CommitPairStatus,
	old: CommitMetadata | null,
	new: CommitMetadata | null,
	intra_diff: IntraDiff | null,
};

export type CommitPairStatus = "Unchanged" | "Modified" | "Added" | "Removed";

export type CommitRange = {
	base_sha: string,
	head_sha: string,
	commits: CommitMetadata[],
};

export type DiffSide = "Old" | "New";

export type Draft = {
	id: string,
	account_id: string,
	target_type: string,
	target_id: string,
	body: string,
	created_at: number,
	updated_at: number,
};

export type EndpointTestResult = {
	api_ok: boolean,
	graphql_ok: boolean,
	api_latency_ms: number,
	graphql_latency_ms: number,
};

export type ErrorKind = { kind: "network" } | { kind: "rate_limited" } | { kind: "auth" } | { kind: "not_found" } | { kind: "conflict" } | { kind: "server" } | { kind: "other"; detail: string };

export type FileTreeSummary = {
	account_id: string,
	pr_id: string,
	head_sha: string,
	directory: string,
	file_count: number,
	viewed_file_count: number,
	additions: number,
	deletions: number,
};

export type GraphiteIntegrationStatus = {
	detected_version: GraphiteVersion | null,
	enabled: boolean,
};

export type GraphiteVersion = {
	raw: string,
};

export type HardConflictDiff = {
	summary: string,
	local_body: string | null,
	server_body: string | null,
	changed_fields: string[],
};

export type HardConflictPayload = {
	mutation_id: string,
	kind: MutationKind,
	target_id: string,
	server_snapshot_json: string,
	predicted_snapshot_json: string,
	diff: HardConflictDiff,
};

export type HighlightKind = "Unchanged" | "Added" | "Removed";

export type HighlightSegment = {
	start: number,
	end: number,
	kind: HighlightKind,
};

export type HighlightedLine = {
	text: string,
	segments: HighlightSegment[],
	side: DiffSide,
};

export type ImageUploadResult = {
	url: string,
	alt: string,
	content_hash: string,
	size_bytes: number,
};

export type InboxChangedEventPayload = {
	account_id: string,
};

export type InboxItem = {
	account_id: string,
	account_login: string,
	account_host: string,
	pr_id: string,
	repo_id: string,
	repo_owner: string,
	repo_name: string,
	pr_number: number,
	title: string,
	state: string,
	draft: boolean,
	head_sha: string,
	base_sha: string,
	mergeable_state: string | null,
	merge_state_status: string | null,
	updated_at: number,
	author_login: string,
	unread_notification_count: number,
	latest_notification_at: number | null,
	pending_overlay: PendingOverlay | null,
};

export type InboxListInput = {
	account_id_filter: string | null,
};

export type InitInboxResponse = {
	active_account_id: string | null,
	accounts: AccountsListResponse,
	subscriptions: RepoSubscriptionItem[],
	inbox: InboxItem[],
	status: SystemStatusResponse | null,
};

export type IntraDiff = {
	hunks: IntraHunk[],
};

export type IntraHunk = {
	old_lines: HighlightedLine[],
	new_lines: HighlightedLine[],
};

export type IpcError = {
	code: string,
	message: string,
};

export type ListDraftsInput = {
	account_id: string,
	target_type: string | null,
	target_id: string | null,
};

export type MergeMethod = "merge" | "squash" | "rebase";

export type MergeableBackoffTickEventPayload = {
	account_id: string,
	pr_id: string,
	attempt: number,
	next_sleep_seconds: number,
};

export type MutationAppliedEventPayload = {
	mutation_id: string,
};

export type MutationFailedEventPayload = {
	mutation_id: string,
	error_kind: ErrorKind,
	retryable: boolean,
	hard_conflict: HardConflictDiff | null,
};

export type MutationHardConflictEventPayload = {
	mutation_id: string,
	conflict: HardConflictPayload,
};

export type MutationKind = "add_comment" | "add_review_comment" | "edit_comment" | "delete_comment" | "add_reaction" | "remove_reaction" | "add_label" | "remove_label" | "set_assignees" | "request_review" | "remove_review_request" | "submit_review" | "resolve_thread" | "unresolve_thread" | "mark_file_viewed" | "unmark_file_viewed" | "update_pr_title" | "update_pr_description" | "set_milestone" | "set_project" | "convert_to_draft" | "mark_ready_for_review" | "enable_auto_merge" | "disable_auto_merge" | "update_branch" | "merge" | "delete_head_ref" | "enqueue_merge_queue" | "dequeue_merge_queue" | "reorder_merge_queue" | "close_pr" | "reopen_pr" | "apply_suggestion" | "apply_suggestion_batch" | "rerun_check_run" | "rerun_check_suite";

export type MutationReconciledEventPayload = {
	mutation_id: string,
};

export type MutationRolledBackEventPayload = {
	mutation_id: string,
};

export type MutationSubmittedEventPayload = {
	mutation: PendingMutationView,
};

export type NetState = { state: "online" } | { state: "offline"; error_kind: ErrorKind };

export type NetworkChangedEventPayload = {
	account_id: string,
	state: NetState,
};

export type NotificationEventPayload = {
	event_id: string,
	account_id: string,
	repo_id: string | null,
	pr_id: string | null,
	event_type: string,
	actor_id: string,
	server_event_id: string,
	title: string,
	body: string,
	fired_at: number,
	deduped: boolean,
};

export type NotificationEventRow = {
	id: string,
	account_id: string,
	repo_id: string | null,
	pr_id: string | null,
	event_type: string,
	actor_id: string,
	server_event_id: string,
	title: string,
	body: string,
	fired_at: number,
	deduped: boolean,
	seen: boolean,
};

export type NotificationItem = {
	id: string,
	reason: string,
	title: string,
	unread: boolean,
	updated_at: number,
	pr_id: string | null,
	repo_owner: string,
	repo_name: string,
};

export type NotificationRule = {
	id: string,
	account_id: string,
	kind: string,
	enabled: boolean,
	config_json: string,
	updated_at: number,
};

export type NotificationsChangedEventPayload = {
	account_id: string,
};

export type NotificationsListInput = {
	account_id: string,
	limit: number | null,
	offset: number | null,
};

export type OptimismLevel = "full" | "cautious" | "none";

export type PagedPrInput = {
	account_id: string,
	pr_id: string,
	limit: number | null,
	offset: number | null,
};

export type PendingMutationView = {
	id: string,
	account_id: string,
	kind: MutationKind,
	optimism: OptimismLevel,
	target_type: string,
	target_id: string,
	status: string,
	retries: number,
	created_at: number,
	updated_at: number,
	last_error: string | null,
	pending_overlay: PendingOverlay | null,
	requires_connection_confirmation: boolean,
};

export type PendingOverlay = {
	mutation_id: string,
	kind: string,
};

export type PrChangedEventPayload = {
	pr_id: string,
};

export type PrCheckSummary = {
	total_runs: number,
	successful_runs: number,
	failed_runs: number,
	pending_runs: number,
	runs: CheckRunSummary[],
};

export type PrDetailSummary = {
	account_id: string,
	pr_id: string,
	repo_id: string,
	pr_number: number,
	title: string,
	body: string,
	state: string,
	draft: boolean,
	base_ref: string,
	base_sha: string,
	head_ref: string,
	head_sha: string,
	mergeable_state: string | null,
	merge_state_status: string | null,
	merge_commit_allowed: boolean | null,
	squash_merge_allowed: boolean | null,
	rebase_merge_allowed: boolean | null,
	delete_branch_on_merge_default: boolean | null,
	viewer_can_merge: boolean | null,
	viewer_can_enable_auto_merge: boolean | null,
	viewer_can_disable_auto_merge: boolean | null,
	viewer_can_update_branch: boolean | null,
	viewer_can_delete_head_ref: boolean | null,
	auto_merge_enabled: boolean | null,
	auto_merge_method: string | null,
	auto_merge_commit_headline: string | null,
	auto_merge_commit_body: string | null,
	auto_merge_enabled_by_login: string | null,
	auto_merge_enabled_at: number | null,
	merge_queue_entry_id: string | null,
	merge_queue_entry_position: number | null,
	merge_queue_entry_state: string | null,
	merge_queue_entry_estimated_ms: number | null,
	branch_protection_summary_json: string | null,
	repo_has_merge_queue: boolean | null,
	head_ref_state: string | null,
	additions: number,
	deletions: number,
	changed_files: number,
	comment_count: number,
	review_count: number,
	thread_count: number,
	check_run_count: number,
	file_count: number,
	updated_at: number,
	body_server_adjusted: boolean,
	pending_overlay: PendingOverlay | null,
};

export type PrFile = {
	account_id: string,
	pr_id: string,
	head_sha: string,
	path: string,
	old_path: string | null,
	previous_path: string | null,
	status: string,
	additions: number,
	deletions: number,
	is_binary: boolean,
	kind: string,
	rename_similarity: number | null,
	is_viewed: boolean,
	patch_blob_sha: string | null,
	viewed_by_account_id: string | null,
	viewed_at_head_sha: string | null,
	pending_overlay: PendingOverlay | null,
};

export type PrFileBlobInput = {
	account_id: string,
	pr_id: string,
	head_sha: string,
	path: string,
	side: string | null,
};

export type PrFileBlobResponse = {
	sha256: string,
	local_path: string,
	mime_type: string,
};

export type PrFilesInput = {
	account_id: string,
	pr_id: string,
	head_sha: string,
};

export type PrFilesResponse = {
	files: PrFile[],
	tree: FileTreeSummary[],
};

export type PrHandleInput = {
	account_id: string,
	pr_id: string,
};

export type PrLabel = {
	label_name: string,
	label_color: string,
	description: string | null,
	pending_overlay: PendingOverlay | null,
};

export type PrMetadataResponse = {
	labels: PrLabel[],
	assignees: PrParticipant[],
	requested_reviewers: PrReviewer[],
	projects: PrProject[],
	milestones: PrMilestone[],
};

export type PrMilestone = {
	milestone_id: string,
	title: string,
	state: string,
	due_on: number | null,
	description: string | null,
	pending_overlay: PendingOverlay | null,
};

export type PrParticipant = {
	user_id: string,
	login: string | null,
	pending_overlay: PendingOverlay | null,
};

export type PrPatchInput = {
	account_id: string,
	pr_id: string,
	head_sha: string,
};

export type PrPatchResponse = {
	patch_blob_sha: string | null,
	patch: string | null,
};

export type PrProject = {
	project_id: string,
	project_title: string,
	item_id: string | null,
	status: string | null,
	updated_at: number,
	pending_overlay: PendingOverlay | null,
};

export type PrPushView = {
	id: number,
	pr_id: string,
	account_id: string,
	head_sha: string,
	base_sha: string,
	observed_at: number,
	push_kind: string,
	supersedes_head_sha: string | null,
};

export type PrReviewer = {
	user_id: string,
	login: string | null,
	reviewer_type: string,
	reviewer_state: string,
	requested_at: number,
	pending_overlay: PendingOverlay | null,
};

export type RangeDiff = {
	old_range: CommitRange,
	new_range: CommitRange,
	commit_pairs: CommitPair[],
	mode: RangeDiffSource,
};

export type RangeDiffSource = "LocalGit" | "RestCompare";

export type RateLimitBucket = {
	account_id: string,
	resource: string,
	remaining: number,
	used: number | null,
	limit_total: number,
	reset_at: number,
	updated_at: number,
};

export type RateLimitBudgetSnapshot = {
	account_id: string,
	resource: string,
	remaining: number,
	used: number | null,
	limit_total: number,
	reset_at_epoch: number,
};

export type RateLimitBypassEventPayload = {
	account_id: string,
	snapshot: RateLimitBudgetSnapshot[],
};

export type RateLimitChangedEventPayload = {
	account_id: string,
};

export type RateLimitPressureEventPayload = {
	account_id: string,
	snapshot: RateLimitBudgetSnapshot[],
};

export type RediscoverSummary = {
	roots: string[],
	discovered: number,
	watched: number,
	skipped_unmapped: number,
	updated_at: number,
};

export type RenderPreviewCtx = {
	repo: string | null,
};

export type RenderPreviewInput = {
	body: string,
	ctx: RenderPreviewCtx,
};

export type RenderedCommentHtml = {
	html: string,
	cache_hit: boolean,
	content_hash: string,
	cache_key: string,
	renderer_version: string,
};

export type RenderedCommentInput = {
	body: string,
	repo: string | null,
};

export type ReorderSavedRepliesInput = {
	account_id: string,
	ordered_ids: number[],
};

export type RepoSubscriptionItem = {
	account_id: string,
	repo_id: string,
	repo_owner: string,
	repo_name: string,
	watch_tier: string,
	last_full_sync_at: number | null,
	updated_at: number,
};

export type RepoSubscriptionsInput = {
	account_id: string,
};

export type ReviewThread = {
	id: string,
	path: string,
	line: number | null,
	side: string | null,
	start_line: number | null,
	start_side: string | null,
	is_outdated: boolean,
	is_resolved: boolean,
	resolved_by_login: string | null,
	updated_at: number,
	comment_count: number,
	pending_overlay: PendingOverlay | null,
};

export type ReviewThreadsPage = {
	threads: ReviewThread[],
	next_offset: number | null,
};

export type SaveDraftInput = {
	id: string,
	account_id: string,
	target_type: string,
	target_id: string,
	body: string,
};

export type SavePatTokenInput = {
	host: string,
	token: string,
};

export type SavedReply = {
	id: number,
	account_id: string,
	name: string,
	body: string,
	sort_order: number,
	created_at: number,
	updated_at: number,
};

export type StackActionInput = {
	account_id: string,
	stack_id: string,
};

export type StackEdge = {
	from_pr_id: string,
	to_pr_id: string,
};

export type StackGraph = {
	stack_id: string,
	account_id: string,
	repo_id: string,
	kind: StackKind,
	nodes: StackNode[],
	edges: StackEdge[],
	warning: StackWarning | null,
	head_pr_id: string | null,
	base_branch: string | null,
	detected_at: number,
	updated_at: number,
};

export type StackKind = "linear" | "dag";

export type StackListInput = {
	account_id: string,
	repo_id: string,
};

export type StackMergeActionInput = {
	account_id: string,
	stack_id: string,
	method: MergeMethod,
};

export type StackNode = {
	pr_id: string,
	pr_number: number,
	title: string,
	state: string,
	position: number,
	parent_pr_id: string | null,
	blocked_by: BlockedByReason[],
	review_decision: string | null,
	check_rollup_state: string | null,
	merge_state_status: string | null,
	base_ref: string,
	head_ref: string,
	base_sha: string,
	head_sha: string,
};

export type StackOperationEventPayload = {
	operation: StackOperationView,
};

export type StackOperationKind = "rebase" | "merge";

export type StackOperationLookupInput = {
	op_id: string,
};

export type StackOperationStatus = "pending" | "running" | "paused_conflict" | "paused_failure" | "succeeded" | "aborted";

export type StackOperationView = {
	id: string,
	stack_id: string,
	account_id: string,
	op_kind: StackOperationKind,
	status: StackOperationStatus,
	current_pr_id: string | null,
	current_step: number | null,
	total_steps: number | null,
	worktree_path: string | null,
	conflict_files: string[],
	last_error: string | null,
	started_at: number,
	updated_at: number,
	finished_at: number | null,
};

export type StackWarning = {
	reason: string,
	diamond_pr_ids: string[],
};

export type StacksChangedEventPayload = {
	account_id: string,
	repo_id: string,
	stacks: StackGraph[],
};

export type StreamHandle = {
	event_name: string,
};

export type SubmitReviewCommentInput = {
	account_id: string,
	payload_json: string,
};

export type SubmittedMutation = {
	mutation_id: string,
	deduped: boolean,
	requires_confirmation: boolean,
	optimism_level: OptimismLevel,
	projected_changes: string[],
};

export type SuggestionBlock = {
	id: string,
	pr_id: string,
	comment_id: string,
	path: string,
	body: string,
	start_line: number,
	end_line: number,
	side: string,
	original_commit_sha: string,
	suggestion_author_login: string,
	is_outdated: boolean,
};

export type SyncReconciledEventPayload = {
	account_id: string,
};

export type SyncSystemSnapshot = {
	focus_state: string,
	tiers: SyncTierSnapshot[],
};

export type SyncTierSnapshot = {
	tier: string,
	last_started_at: number | null,
	last_finished_at: number | null,
	last_error: string | null,
};

export type SystemStatusInput = {
	account_id_filter: string | null,
};

export type SystemStatusResponse = {
	rate_limits: RateLimitBucket[],
	sync: SyncSystemSnapshot,
};

export type TimelineItem = {
	item_id: string,
	item_kind: string,
	body: string,
	author_login: string | null,
	created_at: number,
	updated_at: number,
	review_state: string | null,
	body_server_adjusted: boolean,
	pending_overlay: PendingOverlay | null,
};

export type TimelinePage = {
	items: TimelineItem[],
	next_offset: number | null,
};

export type WorktreeChangedEventPayload = {
	worktree_id: string,
};

export type WorktreeDiscoveryCompletedEventPayload = {
	summary: RediscoverSummary,
};

export type WorktreeView = {
	id: string,
	account_id: string,
	repo_id: string,
	repo_owner: string,
	repo_name: string,
	path: string,
	head_sha: string,
	branch: string,
	dirty: boolean,
	ahead: number,
	behind: number,
	untracked_count: number,
	staged_count: number,
	modified_count: number,
	mapped_pr_id: string | null,
	mapped_pr_number: number | null,
	mapping_confidence: number | null,
	mapping_source: string | null,
	is_app_managed: boolean,
	manual_override_pr_id: string | null,
	manual_override_at: number | null,
	last_cleanup_snapshot_id: string | null,
	created_at: number,
	updated_at: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

