// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ipcAccountsList: () => typedError<AccountsListResponse, IpcError>(__TAURI_INVOKE("ipc_accounts_list")),
	ipcAccountSwitch: (input: AccountSwitchInput) => typedError<AuthAccount, IpcError>(__TAURI_INVOKE("ipc_account_switch", { input })),
	ipcInboxList: (input: InboxListInput) => typedError<InboxItem[], IpcError>(__TAURI_INVOKE("ipc_inbox_list", { input })),
	ipcPrDetailSummary: (input: PrHandleInput) => typedError<{
	account_id: string,
	pr_id: string,
	repo_id: string,
	pr_number: number,
	title: string,
	body: string,
	state: string,
	draft: boolean,
	base_ref: string,
	base_sha: string,
	head_ref: string,
	head_sha: string,
	mergeable_state: string | null,
	merge_state_status: string | null,
	additions: number,
	deletions: number,
	changed_files: number,
	comment_count: number,
	review_count: number,
	thread_count: number,
	check_run_count: number,
	file_count: number,
	updated_at: number,
} | null, IpcError>(__TAURI_INVOKE("ipc_pr_detail_summary", { input })),
	ipcPrTimeline: (input: PagedPrInput) => typedError<TimelinePage, IpcError>(__TAURI_INVOKE("ipc_pr_timeline", { input })),
	ipcPrReviewThreads: (input: PagedPrInput) => typedError<ReviewThreadsPage, IpcError>(__TAURI_INVOKE("ipc_pr_review_threads", { input })),
	ipcPrCheckSummary: (input: CheckSummaryInput) => typedError<PrCheckSummary, IpcError>(__TAURI_INVOKE("ipc_pr_check_summary", { input })),
	ipcPrFiles: (input: PrFilesInput) => typedError<PrFilesResponse, IpcError>(__TAURI_INVOKE("ipc_pr_files", { input })),
	ipcPrPatch: (input: PrPatchInput) => typedError<PrPatchResponse, IpcError>(__TAURI_INVOKE("ipc_pr_patch", { input })),
	ipcRenderedCommentHtml: (input: RenderedCommentInput) => typedError<RenderedCommentHtml, IpcError>(__TAURI_INVOKE("ipc_rendered_comment_html", { input })),
	ipcNotificationsList: (input: NotificationsListInput) => typedError<NotificationItem[], IpcError>(__TAURI_INVOKE("ipc_notifications_list", { input })),
	ipcSystemStatus: (input: SystemStatusInput) => typedError<SystemStatusResponse, IpcError>(__TAURI_INVOKE("ipc_system_status", { input })),
	ipcRepoSubscriptions: (input: RepoSubscriptionsInput) => typedError<RepoSubscriptionItem[], IpcError>(__TAURI_INVOKE("ipc_repo_subscriptions", { input })),
	ipcPrMetadata: (input: PrHandleInput) => typedError<PrMetadataResponse, IpcError>(__TAURI_INVOKE("ipc_pr_metadata", { input })),
	ipcInitInbox: () => typedError<InitInboxResponse, IpcError>(__TAURI_INVOKE("ipc_init_inbox")),
};

/** Events */
export const events = {
	inboxAccountIdChanged: makeEvent<InboxChangedEventPayload>("inbox:account:<id> changed"),
	notificationsAccountIdChanged: makeEvent<NotificationsChangedEventPayload>("notifications:account:<id> changed"),
	prIdChanged: makeEvent<PrChangedEventPayload>("pr:<id> changed"),
	rateLimitAccountIdChanged: makeEvent<RateLimitChangedEventPayload>("rate_limit:account:<id> changed"),
};

/* Types */
export type AccountLocator = {
	host: string,
	login: string,
};

export type AccountSwitchInput = {
	host: string,
	login: string,
};

export type AccountsListResponse = {
	active: AccountLocator | null,
	accounts: AuthAccount[],
};

export type AuthAccount = {
	host: string,
	login: string,
	token_kind: string,
	scopes: string[],
	created_at: number,
	updated_at: number,
	is_active: boolean,
};

export type CheckRunSummary = {
	id: string,
	name: string,
	status: string,
	conclusion: string | null,
	details_url: string | null,
	started_at: number | null,
	completed_at: number | null,
	app_name: string | null,
};

export type CheckSummaryInput = {
	account_id: string,
	pr_id: string,
};

export type FileTreeSummary = {
	account_id: string,
	pr_id: string,
	head_sha: string,
	directory: string,
	file_count: number,
	additions: number,
	deletions: number,
};

export type InboxChangedEventPayload = {
	account_id: string,
};

export type InboxItem = {
	account_id: string,
	pr_id: string,
	repo_id: string,
	repo_owner: string,
	repo_name: string,
	pr_number: number,
	title: string,
	state: string,
	draft: boolean,
	head_sha: string,
	base_sha: string,
	mergeable_state: string | null,
	merge_state_status: string | null,
	updated_at: number,
	author_login: string,
	unread_notification_count: number,
	latest_notification_at: number | null,
};

export type InboxListInput = {
	account_id: string,
};

export type InitInboxResponse = {
	active_account_id: string | null,
	accounts: AccountsListResponse,
	subscriptions: RepoSubscriptionItem[],
	inbox: InboxItem[],
	status: SystemStatusResponse | null,
};

export type IpcError = {
	code: string,
	message: string,
};

export type NotificationItem = {
	id: string,
	reason: string,
	title: string,
	unread: boolean,
	updated_at: number,
	pr_id: string | null,
	repo_owner: string,
	repo_name: string,
};

export type NotificationsChangedEventPayload = {
	account_id: string,
};

export type NotificationsListInput = {
	account_id: string,
	limit: number | null,
	offset: number | null,
};

export type PagedPrInput = {
	account_id: string,
	pr_id: string,
	limit: number | null,
	offset: number | null,
};

export type PrChangedEventPayload = {
	pr_id: string,
};

export type PrCheckSummary = {
	total_runs: number,
	successful_runs: number,
	failed_runs: number,
	pending_runs: number,
	runs: CheckRunSummary[],
};

export type PrDetailSummary = {
	account_id: string,
	pr_id: string,
	repo_id: string,
	pr_number: number,
	title: string,
	body: string,
	state: string,
	draft: boolean,
	base_ref: string,
	base_sha: string,
	head_ref: string,
	head_sha: string,
	mergeable_state: string | null,
	merge_state_status: string | null,
	additions: number,
	deletions: number,
	changed_files: number,
	comment_count: number,
	review_count: number,
	thread_count: number,
	check_run_count: number,
	file_count: number,
	updated_at: number,
};

export type PrFile = {
	account_id: string,
	pr_id: string,
	head_sha: string,
	path: string,
	old_path: string | null,
	status: string,
	additions: number,
	deletions: number,
	is_binary: boolean,
	patch_blob_sha: string | null,
	viewed_by_account_id: string | null,
	viewed_at_head_sha: string | null,
};

export type PrFilesInput = {
	account_id: string,
	pr_id: string,
	head_sha: string,
};

export type PrFilesResponse = {
	files: PrFile[],
	tree: FileTreeSummary[],
};

export type PrHandleInput = {
	account_id: string,
	pr_id: string,
};

export type PrLabel = {
	label_name: string,
	label_color: string,
	description: string | null,
};

export type PrMetadataResponse = {
	labels: PrLabel[],
	assignees: PrParticipant[],
	requested_reviewers: PrReviewer[],
	projects: PrProject[],
	milestones: PrMilestone[],
};

export type PrMilestone = {
	milestone_id: string,
	title: string,
	state: string,
	due_on: number | null,
	description: string | null,
};

export type PrParticipant = {
	user_id: string,
	login: string | null,
};

export type PrPatchInput = {
	account_id: string,
	pr_id: string,
	head_sha: string,
};

export type PrPatchResponse = {
	patch_blob_sha: string | null,
	patch: string | null,
};

export type PrProject = {
	project_id: string,
	project_title: string,
	item_id: string | null,
	status: string | null,
	updated_at: number,
};

export type PrReviewer = {
	user_id: string,
	login: string | null,
	reviewer_type: string,
	reviewer_state: string,
	requested_at: number,
};

export type RateLimitBucket = {
	account_id: string,
	resource: string,
	remaining: number,
	limit_total: number,
	reset_at: number,
	updated_at: number,
};

export type RateLimitChangedEventPayload = {
	account_id: string,
};

export type RenderedCommentHtml = {
	html: string,
	cache_hit: boolean,
	content_hash: string,
	cache_key: string,
	renderer_version: string,
};

export type RenderedCommentInput = {
	body: string,
	repo: string | null,
};

export type RepoSubscriptionItem = {
	account_id: string,
	repo_id: string,
	repo_owner: string,
	repo_name: string,
	watch_tier: string,
	last_full_sync_at: number | null,
	updated_at: number,
};

export type RepoSubscriptionsInput = {
	account_id: string,
};

export type ReviewThread = {
	id: string,
	path: string,
	line: number | null,
	side: string | null,
	start_line: number | null,
	start_side: string | null,
	is_outdated: boolean,
	is_resolved: boolean,
	resolved_by_login: string | null,
	updated_at: number,
	comment_count: number,
};

export type ReviewThreadsPage = {
	threads: ReviewThread[],
	next_offset: number | null,
};

export type SyncSystemSnapshot = {
	focus_state: string,
	tiers: SyncTierSnapshot[],
};

export type SyncTierSnapshot = {
	tier: string,
	last_started_at: number | null,
	last_finished_at: number | null,
	last_error: string | null,
};

export type SystemStatusInput = {
	account_id: string,
};

export type SystemStatusResponse = {
	rate_limits: RateLimitBucket[],
	sync: SyncSystemSnapshot,
};

export type TimelineItem = {
	item_id: string,
	item_kind: string,
	body: string,
	author_login: string | null,
	created_at: number,
	updated_at: number,
	review_state: string | null,
};

export type TimelinePage = {
	items: TimelineItem[],
	next_offset: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

